In [1]:
#Importing the packages

In [24]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

In [6]:
#Reading the homeprice csv file

In [7]:
df=pd.read_csv('homeprice.csv')

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Dealing with missing values
1) Taking median

In [9]:
df.bedrooms.median()

3.5

In [10]:
#Need the data in bedrooms to be an integer

In [11]:
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

3

In [12]:
#inserting this data into NA
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [13]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Linear Regression Model For Predicting House Prices

In [14]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [15]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [16]:
reg.intercept_

383724.9999999998

Predicting Houseprice of a house which is 3000sq feet, 3 bedrooms and 40 years old

In [25]:
reg.predict([[3000,3,40]])

array([444400.])

In [18]:
#y= w1x1 +w2x2 +w3x3 + w0
y= 137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998
y

444399.9999999998

In [26]:
reg.predict([[2500,4,5]])

array([588625.])

Save Model using Pickle

In [20]:
import pickle

In [28]:
with open('linear_reg_model_pickle','wb') as f:
    pickle.dump(reg,f)

In [29]:
with open('linear_reg_model_pickle','rb') as f:
    mp= pickle.load(f)

In [30]:
mp.predict([[2500,4,5]])

array([588625.])

Save Model using Joblib

In [33]:
import joblib

In [34]:
joblib.dump(reg,'linear_reg_model_joblib')

['linear_reg_model_joblib']

In [35]:
mj=joblib.load('linear_reg_model_joblib')

In [37]:
mj.predict([[2500,4,5]])

array([588625.])